### PR TITLE
Move shapes to sub route

### LINKED ISSUE #2: Wildcard for all routes can cause unrelated errors from service worker
When I first ran the project locally, I was getting a lot of errors in the console:

```
Invalid `prisma.shape.findUnique()` invocation:

{
  where: {
    id: NaN
        ~~~
  }
}

Argument id: Got invalid value NaN on prisma.findUniqueShape. Provided Float, expected Int.
```

Turns out the request causing this was to `/sw.js` which I assume is because I've ran other applications on the same port locally.

To avoid confusion for others, I'd suggestion moving the wildcard `$id` in to a sub route such as `s/$id`, `shape/$id`, or `layer/$id`.

Will raise a PR for this.

### PR DESCRIPTION
**Pull request by penx**
Fixes #2

### CODE REVIEW

**Comment by penx** [comment]
@jjenzz is the hash here doing anything?

https://github.com/penx/figma-remix/blob/15b6d296e8bb59c520ad45cc1b10d3314268bf19/app/routes/__$canvas/s/$id.tsx#L30

Or something left from earlier code?

**Comment by jjenzz** [comment]
> Or something left from earlier code?

yeah that's leftover from earlier code so i've just removed it in `main`, thanks.

regarding #2, it seems a bit odd to have to completely rearchitect the project bcos of a dev environment issue. i'm not aware of any `sw.js` files in this project so i'm not sure i fully understand what's happening here but would be good to explore it further so i can maybe propose alternatives.

atm, the project is setup to handle the happy path only so i'll add some error handling at some point. the `$id` route does `Number(params.id!)` which is probably where that `NaN` is coming from, but it would be good to understand why `params.id` is not a number.

**Comment by penx** [comment]
> bcos of a dev environment issue

pretty sure you'd get this on production with things like favicons, robots.txt and anything else that's unlined but a browser or a search engine may look for at the route?

**Comment by penx** [comment]
> completely rearchitect the project

are you saying this because of the diff?

The diff is huge because you kept force pushing to `main` :D

**Comment by penx** [comment]
let me rebase again

**Comment by jjenzz** [comment]
> pretty sure you'd get this on production with things like favicons, robots.txt and anything else that's unlined but a browser or a search engine may look for at the route?

lol, that's a very good point... huge "doh" on my part 🙈

**Review by jjenzz — APPROVED** [review]

**Pull request merged**
